# Generated by Django 5.2.14 on 2026-05-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userembedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userembedding",
            name="id",
        ),
        migrations.AlterField(
            model_name="userembedding",
            name="embed_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
