# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userembedding_id_alter_userembedding_embed_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="faceimage",
            name="pose",
            field=models.CharField(
                choices=[
                    ("front", "Front"),
                    ("left", "Left"),
                    ("right", "Right"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userembedding",
            name="pose",
            field=models.CharField(
                choices=[
                    ("front", "Front"),
                    ("left", "Left"),
                    ("right", "Right"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
    ]
