# Generated by Django 5.2.14 on 2026-05-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_faceimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faceimage",
            name="image",
        ),
        migrations.AddField(
            model_name="faceimage",
            name="processed_image",
            field=models.ImageField(
                blank=True, upload_to="registered_faces/processed/"
            ),
        ),
        migrations.AddField(
            model_name="faceimage",
            name="raw_image",
            field=models.ImageField(default="a.png", upload_to="registered_faces/raw/"),
            preserve_default=False,
        ),
    ]
