# Generated by Django 5.2.14 on 2026-05-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_remove_faceimage_image_faceimage_processed_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaceImage",
        ),
        migrations.DeleteModel(
            name="UserModel",
        ),
    ]
